<a href="https://colab.research.google.com/github/tandat-1305/CTDL-GT/blob/main/Gi%E1%BA%A3i%20thu%E1%BA%ADt%20%C4%91%E1%BB%87%20quy/Knight's__Tour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

move_x = [2, 1, -1, -2, -2, -1, 1, 2]
move_y = [1, 2, 2, 1, -1, -2, -2, -1]

def validateMove(bo, row, col):
    if row < 8 and row >= 0 and col < 8 and col >= 0 and bo[row, col] == 0:
        return True

def solve (bo, row, col, n, counter):
    
    for i in range(8):
        if counter >= 65:
            return True
        new_x = row + move_x[i]
        new_y = col + move_y[i]
        if validateMove(bo, new_x, new_y):
            bo[new_x,new_y] = counter
            if solve(bo,new_x, new_y, n, counter+1):
                return True
            bo[new_x,new_y] = 0
    return False

board = np.zeros((8, 8))

board[3,2] = 1
solve(board,3,2,8,2)
print(board.sum())
print(board)

2080.0
[[38. 53. 30. 57. 14. 63. 28.  7.]
 [31. 58. 39. 62. 29.  8. 13. 64.]
 [52. 37. 54. 25. 56. 15.  6. 27.]
 [59. 32.  1. 40. 61. 26.  9. 12.]
 [36. 51. 60. 55. 24. 11. 16.  5.]
 [45. 48. 33.  2. 41. 18. 21. 10.]
 [50. 35. 46. 43. 20. 23.  4. 17.]
 [47. 44. 49. 34.  3. 42. 19. 22.]]
